# 1. Delivery Pipeline Definition
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: cicd-app
description: cicd-app application 
serialPipeline:
 stages:
 - targetId: staging
 - targetId: prod
---

# 2. Staging Environment Target

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: staging
description: staging cluster
gke:
 cluster: projects/innate-valor-451418-i0/locations/us-central1-a/clusters/stg-pipeline
---

# 3. Production Environment Target

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prod
description: prod cluster
requireApproval: true
gke:
 cluster: projects/innate-valor-451418-i0/locations/us-central1-a/clusters/prod-pipeline
